"""The 4-month system design curriculum: one topic per day, in order.

Each entry is (title, what to cover, hands-on lab). The bot sends them in order, one per day.
Edit freely: reorder, replace or add topics. LEVELS maps day ranges to a difficulty label.
"""

LEVELS = [
    (1, 30, "Easy"),
    (31, 60, "Medium"),
    (61, 90, "Hard"),
    (91, 120, "Big Tech Architecture"),
]

CURRICULUM = [
    # ---------- Easy (days 1-30) ----------
    ("How the web works: from URL to response",
     "DNS resolution, TCP and TLS handshakes, HTTP request/response, where time is spent.",
     "Use curl -w timing, dig and Wireshark/tcpdump to trace one request and break down its latency."),
    ("Latency vs throughput and the numbers every engineer should know",
     "Latency, throughput, bandwidth, percentiles (p50/p99), memory vs disk vs network costs.",
     "Benchmark an HTTP endpoint with wrk or hey; plot p50/p99 as concurrency grows."),
    ("Back-of-the-envelope estimation",
     "QPS, storage, bandwidth and memory estimates; powers of two; read/write ratios.",
     "Estimate storage and QPS for a Twitter-like app, then write a small Python calculator for it."),
    ("Vertical vs horizontal scaling",
     "Scale up vs scale out, limits of each, why statelessness enables scale-out.",
     "Run 1 vs 3 app containers behind Nginx with Docker Compose and compare throughput."),
    ("Stateless vs stateful services",
     "Where state lives, sticky sessions, externalising session state.",
     "Move in-memory sessions of a small Flask/Express app into Redis and kill instances freely."),
    ("Load balancing fundamentals",
     "L4 vs L7, round robin, least connections, consistent hashing, health checks.",
     "Configure HAProxy or Nginx with different algorithms; kill a backend and watch health checks."),
    ("Reverse proxies and API gateways",
     "TLS termination, routing, auth, rate limiting, request aggregation.",
     "Put Nginx or Kong in front of two services with path routing and a basic auth plugin."),
    ("Relational databases and ACID",
     "Transactions, isolation levels, anomalies (dirty read, lost update, write skew).",
     "Reproduce a lost update in PostgreSQL with two sessions, then fix it with SELECT FOR UPDATE."),
    ("Database indexing",
     "B-tree indexes, composite indexes, covering indexes, cost of writes, EXPLAIN plans.",
     "Load 1M rows in Postgres, compare EXPLAIN ANALYZE before and after adding indexes."),
    ("NoSQL database types",
     "Key-value, document, wide-column, graph; data modelling by access pattern; when to choose each.",
     "Model the same e-commerce order data in Postgres and MongoDB and compare queries."),
    ("Caching fundamentals",
     "Cache-aside, TTLs, eviction policies (LRU/LFU), hit ratio, what to cache.",
     "Add Redis cache-aside to a slow API and measure hit ratio and latency improvement."),
    ("Content Delivery Networks (CDNs)",
     "Edge caching, origin pull vs push, cache keys, invalidation, anycast.",
     "Serve a static site through Cloudflare free tier or a local Varnish and inspect cache headers."),
    ("HTTP caching",
     "Cache-Control, ETag, Last-Modified, conditional requests, browser vs shared caches.",
     "Implement ETag support in a small API and verify 304 responses with curl."),
    ("Authentication and sessions",
     "Cookies, sessions, JWTs, refresh tokens, OAuth2 basics, trade-offs of stateless tokens.",
     "Build login with JWT access and refresh tokens; implement token revocation."),
    ("Storage types: block, file and object",
     "Block vs file vs object storage, S3 semantics, presigned URLs, durability.",
     "Run MinIO locally and implement direct-to-storage uploads with presigned URLs."),
    ("Message queues basics",
     "Async processing, producers/consumers, acks, visibility timeout, dead-letter queues.",
     "Build a RabbitMQ worker that processes image jobs, with retries and a DLQ."),
    ("Pub/sub vs point-to-point messaging",
     "Topics vs queues, fan-out, competing consumers, ordering guarantees.",
     "Use Redis Streams or RabbitMQ exchanges to fan out one event to three services."),
    ("Synchronous vs asynchronous communication",
     "Request/response vs events, webhooks, coupling, latency vs reliability trade-offs.",
     "Convert a synchronous order -> email call into an async event and measure response time."),
    ("Real-time communication: polling, long polling, WebSockets, SSE",
     "How each works, connection costs, when to choose which.",
     "Build the same live counter with long polling, SSE and WebSockets; compare connections and latency."),
    ("REST vs GraphQL vs gRPC",
     "Resource modelling, over/under-fetching, protobuf, streaming, browser support.",
     "Expose one service via REST and gRPC; benchmark payload size and latency."),
    ("API design best practices",
     "Naming, pagination (offset vs cursor), versioning, error formats, idempotency keys.",
     "Design and implement cursor pagination for a large table; compare with OFFSET on 1M rows."),
    ("Idempotency and safe retries",
     "Idempotent operations, idempotency keys, retries with exponential backoff and jitter.",
     "Build a payment endpoint with idempotency keys; fire duplicate requests and prove one charge."),
    ("Rate limiting algorithms",
     "Fixed window, sliding window, token bucket, leaky bucket; trade-offs.",
     "Implement token bucket and sliding window in Python; load test with bursts."),
    ("Monolith vs microservices",
     "Modular monolith, service boundaries, team topology, costs of distribution.",
     "Split one module out of a small monolith into a service; list what got harder."),
    ("Availability, SLAs, SLOs and the nines",
     "Availability math, serial vs parallel components, SLIs/SLOs/SLAs, error budgets.",
     "Calculate system availability for a 5-component architecture; define SLOs for an API."),
    ("Redundancy, failover and health checks",
     "Active-passive vs active-active, failover detection, split brain basics.",
     "Set up Postgres primary + standby with Docker and perform a manual failover."),
    ("Observability basics: logs, metrics and traces",
     "Structured logging, RED/USE metrics, distributed tracing concepts.",
     "Instrument a two-service app with OpenTelemetry, Prometheus and Grafana."),
    ("Database replication basics",
     "Primary-replica, read replicas, sync vs async, replication lag.",
     "Set up Postgres streaming replication; write to primary, read from replica, observe lag."),
    ("Data serialization and encoding",
     "JSON vs Protobuf vs Avro, schema evolution, backward/forward compatibility.",
     "Evolve a Protobuf schema across two service versions without breaking either."),
    ("Design walkthrough: URL shortener",
     "Interview framework: requirements, estimates, API, data model, high-level design, deep dives.",
     "Build a working URL shortener with base62 IDs, Redis cache and Postgres; load test it."),

    # ---------- Medium (days 31-60) ----------
    ("Database sharding and partitioning",
     "Range vs hash vs directory partitioning, hot spots, resharding, cross-shard queries.",
     "Shard a users table across 3 Postgres instances with app-level routing; add a 4th shard."),
    ("Consistent hashing",
     "Hash rings, virtual nodes, minimal remapping, use in caches and databases.",
     "Implement a consistent hash ring with virtual nodes; measure key movement when adding nodes."),
    ("Replication deep dive",
     "Leader-follower, multi-leader, leaderless; read-your-writes, monotonic reads, conflict handling.",
     "Simulate replication lag and implement read-your-writes consistency in the app layer."),
    ("Advanced caching patterns",
     "Write-through, write-back, write-around; cache stampede, thundering herd, hot keys.",
     "Reproduce a cache stampede under load, then fix it with request coalescing and jittered TTLs."),
    ("Distributed caches: Redis and Memcached",
     "Redis cluster, replication, persistence (RDB/AOF), eviction, data structures.",
     "Run a 6-node Redis Cluster in Docker, kill a master and watch failover."),
    ("CAP theorem and PACELC",
     "Partitions, consistency vs availability, latency trade-offs, classifying real databases.",
     "Partition a 3-node cluster with Docker network disconnect and observe CP vs AP behaviour."),
    ("Consistency models",
     "Linearizability, sequential, causal, eventual consistency; session guarantees.",
     "Write a test that detects stale reads against an eventually consistent store."),
    ("Apache Kafka deep dive",
     "Topics, partitions, offsets, consumer groups, retention, ordering, rebalancing.",
     "Run Kafka in Docker; build a producer and consumer group; trigger and observe a rebalance."),
    ("Message delivery semantics",
     "At-most-once, at-least-once, exactly-once; deduplication and idempotent consumers.",
     "Crash a consumer mid-batch, show duplicates, then fix with idempotent processing."),
    ("Event-driven architecture and event sourcing",
     "Events as source of truth, event stores, projections, replay, snapshots.",
     "Build a bank account with event sourcing; rebuild balances by replaying events."),
    ("CQRS",
     "Separate read and write models, eventual consistency between them, when it's worth it.",
     "Add a read-optimised projection (Elasticsearch or Redis) fed by events from a write model."),
    ("Search systems and inverted indexes",
     "Tokenization, inverted indexes, TF-IDF/BM25, Elasticsearch shards and replicas.",
     "Index 100k products in Elasticsearch; implement search with filters and relevance tuning."),
    ("Wide-column and time-series databases",
     "Cassandra data modelling, partition keys, LSM storage; time-series DBs for metrics.",
     "Model sensor data in Cassandra or TimescaleDB and query by device and time range."),
    ("Design: distributed rate limiter",
     "Rate limiting across many servers, Redis-based counters, Lua atomicity, race conditions.",
     "Build a Redis + Lua sliding window rate limiter shared by 3 API instances."),
    ("Service discovery and service mesh",
     "Client vs server-side discovery, Consul/etcd, sidecars, Envoy, Istio basics.",
     "Register services in Consul and route between them; add Envoy as a sidecar."),
    ("Resilience patterns",
     "Timeouts, retries with backoff and jitter, circuit breakers, bulkheads, fallbacks.",
     "Inject latency into a dependency with toxiproxy; add a circuit breaker and compare."),
    ("Batch vs stream processing",
     "MapReduce, Spark, Flink, Lambda vs Kappa architecture.",
     "Compute the same daily aggregate with a Spark batch job and a streaming job."),
    ("Data pipelines and change data capture",
     "ETL vs ELT, CDC with Debezium, outbox, data warehouses vs lakes.",
     "Stream Postgres changes to Kafka with Debezium and update a search index."),
    ("Media upload and processing pipelines",
     "Chunked/resumable uploads, transcoding, thumbnails, async workers, storage tiers.",
     "Build resumable chunked uploads to MinIO with an FFmpeg transcoding worker."),
    ("Geospatial indexing",
     "Geohash, quadtrees, S2, Uber H3, nearby search, proximity queries.",
     "Implement 'find nearby drivers' with Redis GEO and with geohash prefixes."),
    ("Unique ID generation",
     "UUIDs, ULIDs, database sequences, Twitter Snowflake, ordering and collisions.",
     "Implement a Snowflake ID generator and test uniqueness across concurrent workers."),
    ("Probabilistic data structures",
     "Bloom filters, HyperLogLog, count-min sketch; memory vs accuracy trade-offs.",
     "Use a Bloom filter to skip DB lookups; count unique visitors with Redis HyperLogLog."),
    ("Storage engine internals: B-trees vs LSM trees",
     "Write-ahead logs, memtables, SSTables, compaction, read/write amplification.",
     "Write a tiny LSM key-value store in Python with a WAL and compaction."),
    ("Design: notification system",
     "Push, SMS, email channels; templates, preferences, retries, rate limits, dedup.",
     "Build a multi-channel notifier with a queue, per-user preferences and retry logic."),
    ("Design: news feed",
     "Fan-out on write vs read, celebrity problem, ranking, feed caching.",
     "Implement fan-out on write with Redis sorted sets and a hybrid path for celebrities."),
    ("Design: chat system",
     "1:1 and group chat, WebSocket gateways, message ordering, delivery receipts, presence.",
     "Build a WebSocket chat with Redis pub/sub across 2 gateway instances and read receipts."),
    ("Design: typeahead / autocomplete",
     "Tries, top-k suggestions, precomputation, caching, personalisation.",
     "Build a trie-based autocomplete service with top-k caching; load test it."),
    ("Design: web crawler",
     "URL frontier, politeness, dedup, distributed crawling, robots.txt.",
     "Write a polite multi-worker crawler with a Redis frontier and content dedup."),
    ("Deployment strategies",
     "Rolling, blue-green, canary, feature flags, rollback, database compatibility.",
     "Do a canary release with Nginx weighted routing and roll back on error rate."),
    ("Design: ticket booking system (like BookMyShow)",
     "Seat locking, concurrency control, holds with expiry, payments, overbooking prevention.",
     "Build seat booking with Redis holds and DB constraints; hammer it with concurrent buyers."),

    # ---------- Hard (days 61-90) ----------
    ("Consensus with Raft",
     "Leader election, log replication, terms, safety, membership changes.",
     "Run an etcd cluster, kill the leader, and watch election; read the Raft visualisation."),
    ("Coordination services: ZooKeeper and etcd",
     "Leader election, configuration, locks, watches, Paxos vs Raft at a high level.",
     "Implement leader election for 3 workers using etcd leases."),
    ("Distributed transactions: two-phase commit",
     "2PC, coordinator failure, blocking, XA, why most systems avoid it.",
     "Simulate 2PC across two databases and kill the coordinator mid-commit."),
    ("Sagas and the transactional outbox",
     "Choreography vs orchestration, compensating actions, outbox + relay.",
     "Implement an order saga (order, payment, inventory) with an outbox and compensation."),
    ("Distributed locks and fencing tokens",
     "Lock leases, Redlock and its critique, fencing tokens, when locks are unsafe.",
     "Show a GC-pause lock violation, then fix it with fencing tokens."),
    ("Time and ordering in distributed systems",
     "Clock skew, NTP, Lamport clocks, vector clocks, hybrid logical clocks.",
     "Implement Lamport and vector clocks for 3 processes and detect concurrent events."),
    ("Dynamo-style leaderless replication",
     "Quorums (N/R/W), sloppy quorums, hinted handoff, read repair, Merkle-tree anti-entropy.",
     "Build a tiny 3-node quorum KV store and test different R/W settings under node failure."),
    ("CRDTs and collaborative editing",
     "Conflict-free replicated data types, operational transformation, offline sync.",
     "Build a collaborative text editor with Yjs and two clients going offline and back."),
    ("Multi-region active-active architecture",
     "Geo routing, data replication across regions, conflict resolution, failover.",
     "Simulate two regions with Docker networks and test region failover with DNS/proxy."),
    ("Globally consistent databases: Spanner and CockroachDB",
     "TrueTime, external consistency, distributed SQL, Raft groups per range.",
     "Run a 3-node CockroachDB cluster, kill a node and observe range rebalancing."),
    ("Stream processing at scale",
     "Windowing, watermarks, late data, stateful processing, exactly-once with checkpoints.",
     "Build a Flink or Kafka Streams job with tumbling windows and late events."),
    ("Backpressure, load shedding and admission control",
     "Queue limits, adaptive concurrency, priority shedding, graceful degradation.",
     "Overload a service, then add adaptive concurrency limits and priority shedding."),
    ("Cascading failures and metastable failures",
     "Retry storms, thundering herds, timeouts chains, metastable states, recovery.",
     "Reproduce a retry storm across 3 services and fix it with retry budgets."),
    ("Chaos engineering",
     "Steady-state hypotheses, blast radius, fault injection, game days.",
     "Use Chaos Toolkit or Pumba to kill containers and add latency; verify SLOs hold."),
    ("Observability at scale and SLO engineering",
     "SLIs, SLOs, error budgets, burn-rate alerts, high-cardinality metrics, tracing sampling.",
     "Define SLOs and multi-window burn-rate alerts in Prometheus for a sample service."),
    ("Zero-downtime migrations",
     "Expand/contract schema changes, dual writes, backfills, shadow reads.",
     "Rename a hot column in Postgres with zero downtime using expand/contract."),
    ("Capacity planning and cost optimization",
     "Load modelling, headroom, autoscaling, reserved vs spot, cost per request.",
     "Load test a service, derive capacity per instance, and build a cost model spreadsheet."),
    ("Security in system design",
     "OAuth2/OIDC, mTLS, secrets management, zero trust, encryption at rest and in transit.",
     "Set up mTLS between two services and manage their secrets with Vault."),
    ("Multi-tenancy",
     "Silo vs pool vs bridge models, tenant isolation, noisy neighbours, per-tenant limits.",
     "Implement row-level security in Postgres for a multi-tenant SaaS schema."),
    ("Design: payment system",
     "Idempotency, double-entry ledgers, PSP integration, reconciliation, retries.",
     "Build a double-entry ledger with idempotent transfers and a reconciliation job."),
    ("Design: ride hailing (like Uber/Ola)",
     "Location ingestion, driver matching, geo-sharding, surge pricing, trip state machine.",
     "Simulate 1,000 drivers sending locations and match riders with H3 cells."),
    ("Design: video streaming platform",
     "Upload, transcoding ladder, adaptive bitrate (HLS/DASH), CDN, recommendations.",
     "Transcode a video into an HLS bitrate ladder with FFmpeg and play it with hls.js."),
    ("Design: distributed key-value store",
     "Partitioning, replication, consistency tuning, failure detection with gossip.",
     "Extend your earlier quorum KV store with consistent hashing and gossip membership."),
    ("Design: distributed message queue",
     "Append-only logs, partitions, replication, ISR, consumer offsets, retention.",
     "Build a mini log-based queue with partitions and consumer offsets in Go or Python."),
    ("Design: collaborative document editor (like Google Docs)",
     "OT vs CRDT, presence, cursors, versioning, permission checks at scale.",
     "Add presence and version history to your earlier Yjs editor with a persistent backend."),
    ("Design: stock exchange / order matching engine",
     "Order books, matching algorithms, low-latency design, sequencers, market data fan-out.",
     "Implement a price-time priority matching engine and benchmark orders per second."),
    ("Design: distributed job scheduler",
     "Cron at scale, leases, exactly-once execution, retries, priority queues.",
     "Build a scheduler with multiple workers using Postgres SKIP LOCKED leases."),
    ("Design: real-time analytics (ad click aggregation)",
     "High-volume ingestion, windowed aggregation, dedup, reconciliation, OLAP stores.",
     "Aggregate clicks per ad per minute with Kafka and ClickHouse; verify counts."),
    ("Design: metrics monitoring and alerting system",
     "Time-series ingestion, downsampling, query engine, alert evaluation.",
     "Build a mini metrics pipeline: push metrics, store in TimescaleDB, alert on thresholds."),
    ("Staff-level mock: global flash sale system",
     "Ambiguous requirements, inventory correctness under extreme spikes, queueing, fairness.",
     "Load test an inventory reservation service at 10k req/s with Redis atomic decrements."),

    # ---------- Big Tech Architecture (days 91-120) ----------
    ("Netflix: Open Connect and global video delivery",
     "Own CDN appliances in ISPs, proactive caching, steering, AWS control plane.",
     "Build a mini CDN: origin + two edge caches with Nginx and a steering service."),
    ("PhonePe: UPI payments at massive scale",
     "Handling billions of UPI transactions, bank integrations, peak handling, reliability.",
     "Build a mock UPI flow: PSP app, switch and two banks with timeouts and reconciliation."),
    ("Amazon: service-oriented architecture and DynamoDB",
     "The Dynamo paper, the shift to SOA, two-pizza teams, DynamoDB partitioning.",
     "Model an access-pattern-first single-table design in DynamoDB Local."),
    ("Paytm: payments and wallet architecture",
     "Wallet ledger, payment gateway, high-traffic events, fraud checks.",
     "Build a wallet service with a ledger, balance holds and idempotent top-ups."),
    ("Instagram: scaling Django, PostgreSQL and the feed",
     "Sharded Postgres, ID generation, Cassandra usage, feed ranking, Python at scale.",
     "Implement Instagram's sharded ID scheme in Postgres (timestamp + shard + sequence)."),
    ("Flipkart: Big Billion Days flash sale",
     "Traffic prediction, inventory, queueing, graceful degradation, load testing culture.",
     "Build a sale-day inventory service with a waiting room queue and load test it."),
    ("Uber: real-time dispatch and geospatial at scale",
     "Dispatch matching, H3, Ringpop, schemaless storage, microservices evolution.",
     "Build supply/demand matching on H3 cells with a simple ETA heuristic."),
    ("Swiggy: delivery assignment and ETA prediction",
     "Order assignment, batching, ETA models, peak-hour scaling.",
     "Simulate order-to-delivery-partner assignment with batching and compare strategies."),
    ("WhatsApp: millions of connections per server",
     "Erlang/BEAM, connection handling, small team at huge scale, E2E encryption overview.",
     "Write a WebSocket server and test how many idle connections one machine can hold."),
    ("Zomato: handling peak events like New Year's Eve",
     "Peak traffic preparation, caching, search and discovery, real-time order tracking.",
     "Build real-time order tracking with SSE and load test it with thousands of clients."),
    ("Netflix: resilience engineering",
     "Hystrix, Zuul, Chaos Monkey, regional evacuation, fallback design.",
     "Add circuit breakers and fallbacks to a 3-service app and run a chaos experiment."),
    ("Razorpay: payment gateway reliability",
     "Smart routing across banks, success-rate optimisation, idempotency, webhooks.",
     "Build a payment router that picks the gateway with the best recent success rate."),
    ("Discord: storing trillions of messages",
     "MongoDB to Cassandra to ScyllaDB, data services, hot partitions, request coalescing.",
     "Model message storage by channel and time bucket in ScyllaDB/Cassandra."),
    ("Hotstar: streaming to tens of millions of concurrent viewers",
     "IPL-scale live streaming, pre-scaling, CDN strategy, ladder-based autoscaling.",
     "Build a live HLS stream with FFmpeg and simulate a viewer surge against a cache."),
    ("Google: GFS, MapReduce and Bigtable",
     "The foundational papers, master/chunkserver design, tablets, SSTables.",
     "Implement a mini MapReduce word count across worker processes."),
    ("UPI and NPCI: the architecture of India's payment switch",
     "VPA resolution, PSPs, issuer/acquirer banks, two-factor flow, scale and timeouts.",
     "Extend your mock UPI flow with VPA lookup and deemed/pending transaction handling."),
    ("Twitter/X: timelines and Snowflake",
     "Fan-out service, timeline caching in Redis, Snowflake IDs, search.",
     "Rebuild a mini home timeline with fan-out on write and Redis lists."),
    ("Zerodha: a high-scale trading platform with a small team",
     "Kite architecture, market data streaming, simplicity choices, Postgres usage.",
     "Stream live mock tick data over WebSockets to many clients efficiently."),
    ("LinkedIn: Kafka and the data infrastructure",
     "Why Kafka was built, the log as a unifying abstraction, Espresso, Venice.",
     "Build an activity tracking pipeline: events to Kafka to a consumer that builds stats."),
    ("Myntra: handling end-of-season sale traffic",
     "Peak sale architecture, caching catalog and prices, checkout scaling.",
     "Cache a product catalog with stampede protection and test it under sale-like load."),
    ("Slack: real-time messaging architecture",
     "Channel servers, gateway servers, message fan-out, Vitess for MySQL sharding.",
     "Build channel-based fan-out with a gateway layer and consistent hashing of channels."),
    ("Dream11: scaling for IPL fantasy sports spikes",
     "Huge traffic spikes at match start, leaderboard computation, pre-scaling.",
     "Build a real-time leaderboard with Redis sorted sets for 1M users."),
    ("Amazon S3: durability and storage architecture",
     "11 nines of durability, erasure coding, ShardStore, strong consistency launch.",
     "Implement simple erasure coding (Reed-Solomon) and recover from lost shards."),
    ("Blinkit and Zepto: 10-minute delivery",
     "Dark stores, inventory accuracy, demand forecasting, picker and rider assignment.",
     "Build a dark-store inventory service with reservations and a demand-forecast stub."),
    ("Shopify: pods and the modular monolith at flash-sale scale",
     "Pod architecture, modular monolith, handling flash sales, MySQL sharding.",
     "Split a sample monolith into enforced modules and route tenants to pods."),
    ("Aadhaar: identity at a billion-person scale",
     "Biometric deduplication, authentication APIs, open-source stack, scale-out design.",
     "Build a mock identity auth API with OTP flow, rate limiting and audit logs."),
    ("Meta: TAO and Memcache at scale",
     "The social graph store, memcache leases, regional pools, invalidations via MySQL.",
     "Implement memcache-style leases to prevent stale sets and thundering herds."),
    ("Instagram: Explore recommendations",
     "Candidate generation, ranking stages, embeddings, serving infrastructure.",
     "Build a two-stage recommender: embedding retrieval with FAISS, then a simple ranker."),
    ("Cloudflare: global edge network",
     "Anycast, edge compute (Workers), DDoS mitigation, config propagation.",
     "Deploy a Cloudflare Worker (free tier) doing edge caching and rate limiting."),
    ("Capstone: design a PhonePe/Paytm-style payments app end to end",
     "Full staff-level mock interview combining everything: UPI, wallet, ledger, scale, failure.",
     "Write a full design doc with diagrams, then build the riskiest part and load test it."),
]
